[project]
name = "obs-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "obs-websocket-py>=1.0",
    "obsws-python>=1.8.0",
]
